name: Deploy Flask App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m venv venv
          venv/bin/pip install -r requirements.txt
      - name: Build and deploy
        run: |
          venv/bin/python setup.py install
          venv/bin/gunicorn --bind 0.0.0.0:$PORT wsgi:app
      - name: Deploy to Render
        uses: render-examples/git-auto-deploy@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          render_token: ${{ secrets.RENDER_TOKEN }}
          render_app_name: my-app-name
